name: Deploy to Freemius

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Plugin to Freemius
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r libre-bite.zip . -x "*.git*" ".github*" ".DS_Store" "*.zip"

      - name: Deploy to Freemius
        uses: buttonizer/freemius-deploy@v0.1.2
        with:
          developer_id: ${{ secrets.FREEMIUS_DEVELOPER_ID }}
          plugin_id: ${{ secrets.FREEMIUS_PLUGIN_ID }}
          public_key: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          secret_key: ${{ secrets.FREEMIUS_SECRET_KEY }}
          plugin_slug: librebite
          file_name: libre-bite.zip
          release_mode: released
          version: ${{ github.ref_name }}
          sandbox: false
