name: Deploy to Freemius

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Plugin to Freemius
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Freemius Deployment
        uses: freemius/deploy-on-freemius@v1
        with:
          developer_id: ${{ secrets.FREEMIUS_DEVELOPER_ID }}
          plugin_id: ${{ secrets.FREEMIUS_PLUGIN_ID }}
          public_key: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          secret_key: ${{ secrets.FREEMIUS_SECRET_KEY }}
          plugin_path: .
          zip_name: libre-bite.zip
